# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/homeimprovementtracker?currentSchema=homeimprovementtracker
spring.datasource.username=hituser
spring.datasource.password=hituser
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Actuator Configuration with Dependency Health Checks
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.status.order=DOWN,OUT_OF_SERVICE,UP,UNKNOWN
management.health.db.enabled=true
management.health.defaults.enabled=true
management.health.diskSpace.enabled=true
management.health.ping.enabled=true

# Swagger UI enabled for dev profile
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
